### PR TITLE
add ListHostMetricNames

### PR DESCRIPTION
**Pull request by astj**
Described at https://mackerel.io/ja/api-docs/entry/hosts#metric-names

### CODE REVIEW

**Comment by itchyny** [comment]
How about adding metric names of service api as well?  https://mackerel.io/ja/api-docs/entry/services#metric-names

**Comment by astj** [comment]
Sure. I'll do.

**Comment by astj** [comment]
Opened #69 for ListServiceMetricNames, since the name of this branch is not for it.

**Comment by itchyny** [comment]
LGTM

**Pull request merged**
