### PR TITLE
implement aws-integrations APIs

### PR DESCRIPTION
**Pull request by Gompei**
Hello:wave:
aws-integrations APIs did not appear to be implemented, so I implemented it.
I would like to use terraform-provider-mackerel to manage my AWS integration settings, and I think this pull request needs to be merged for that purpose.
I will write a separate PR for the terraform-provider-mackerel implementation as soon as this PR is merged.
ref: https://mackerel.io/api-docs/entry/aws-integration

### CODE REVIEW

**Review by lufia — COMMENTED** [review]
Awesome, thanks a lot for your contribution!

**Comment by Gompei** [comment]
@lufia Thank you very much for the review.
I accepted your suggestions and added commits to this pull request.

**Review by lufia — APPROVED** [review]
@Gompei  Thank you!

**Comment by lufia** [comment]
v0.18.0 released

**Pull request merged**
